config/routes.rb
Rails.application.routes.draw do
  resources :lists
  #get 'home/index'
  get 'home/about'
  root 'home#index'
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/list.rb
class List < ApplicationRecord
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index
  end

  def about
  end
  
end

app/controllers/lists_controller.rb
class ListsController < ApplicationController
  before_action :set_list, only: %i[ show edit update destroy ]

  # GET /lists or /lists.json
  def index
    @lists = List.all
  end

  # GET /lists/1 or /lists/1.json
  def show
  end

  # GET /lists/new
  def new
    @list = List.new
  end

  # GET /lists/1/edit
  def edit
  end

  # POST /lists or /lists.json
  def create
    @list = List.new(list_params)

    respond_to do |format|
      if @list.save
        format.html { redirect_to list_url(@list), notice: "List was successfully created." }
        format.json { render :show, status: :created, location: @list }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @list.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /lists/1 or /lists/1.json
  def update
    respond_to do |format|
      if @list.update(list_params)
        format.html { redirect_to list_url(@list), notice: "List was successfully updated." }
        format.json { render :show, status: :ok, location: @list }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @list.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /lists/1 or /lists/1.json
  def destroy
    @list.destroy

    respond_to do |format|
      format.html { redirect_to lists_url, notice: "List was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_list
      @list = List.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def list_params
      params.require(:list).permit(:title, :author, :genre, :year)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/lists_helper.rb
module ListsHelper
end

app/views/home/_header.html.erb
<nav class="navbar navbar-expand-lg navbar-dark bg-dark">
    <img src="https://cdn-icons-png.flaticon.com/512/327/327116.png" alt="A book illustration" width="30" height="24" class="align-text-top">
    
    <li class="nav-item">
      <%= link_to 'Book App', root_path, class:"navbar-brand" %>
    </li>
    
  
  <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
    <span class="navbar-toggler-icon"></span>
  </button>

  <div class="collapse navbar-collapse" id="navbarSupportedContent">
    <ul class="navbar-nav mr-auto">
      
      <li class="nav-item">
        <%= link_to "Books", lists_path, class:"nav-link" %>
      </li>

      <li class="nav-item">
        <%= link_to "Add Book", new_list_path, class:"nav-link" %>
      </li>

      <li class="nav-item">
        <%= link_to "About", home_about_path, class:"nav-link" %>
      </li>

      <form class="d-flex">
        <input class="form-control me-2" type="search" placeholder="Search" aria-label="Search">
        <button class="btn btn-outline-success" type="submit">Search</button>
      </form>
    </div>
  </div>
</nav>

app/views/home/about.html.erb
<h1>About the project</h1>

<p>An application to register and display books read.</p>

<p> <strong>Technologies</strong>:
  <ul class="list-group">
	  <li class="list-group-item">Ruby 3.0</li>
	  <li class="list-group-item">Rails 7.0</li>
	  <li class="list-group-item">HTML</li>
	  <li class="list-group-item">CSS</li>
	  <li class="list-group-item">Bootstrap</li>
	  <li class="list-group-item">
	  	SQLite 3.0
	  </li>
</ul>

</p>

app/views/home/index.html.erb
<h1>Hello World! </h1>
Beginning my Rails webpage: a book list. 

app/views/layouts/_alerts.html.erb
<div class="alert alert-warning alert-dismissible fade show" role="alert">
  <%= notice %>
  <button type="button" class="btn-close" data-bs-dismiss="alert" aria-label="Close"></button>
</div>

app/views/layouts/application.html.erb
<!doctype html>
<html lang="en">
  <head>
    <!-- Required meta tags -->
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">

    <!-- Bootstrap CSS -->
      <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.5.2/css/bootstrap.min.css" integrity="sha384-JcKb8q3iqJ61gNV9KGb8thSsNjpSL0n8PARn9HuZOnIxN0hoP+VmmDGMN5t9UJ0Z" crossorigin="anonymous">


    <title>Book List App</title>
        <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
  </head>
  <body>
  
      <%= render 'home/header' %>
  
    <div class="container">
    <br/>
      <% if notice %>
        <%= render 'layouts/alerts' %>
      <% end %>

      <%= yield %>
    </div>

     <!-- Optional JavaScript -->
    <!-- jQuery first, then Popper.js, then Bootstrap JS -->
    <script src="https://code.jquery.com/jquery-3.5.1.slim.min.js" integrity="sha384-DfXdz2htPH0lsSSs5nCTpuj/zy4C+OGpamoFVy38MVBnE+IbbVYUew+OrCXaRkfj" crossorigin="anonymous"></script>
    <script src="https://cdn.jsdelivr.net/npm/popper.js@1.16.1/dist/umd/popper.min.js" integrity="sha384-9/reFTGAW83EW2RDu2S0VKaIzap3H66lZH81PoYlFhbGU+6BZp6G7niu735Sk7lN" crossorigin="anonymous"></script>
    <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.5.2/js/bootstrap.min.js" integrity="sha384-B4gt1jrGC7Jh4AgTPSdUtOBvfO8shuf57BaghqFfPlYxofvL8/KUEfYiJOMMV+rV" crossorigin="anonymous"></script>
    
  </body>
</html>

app/views/lists/_form.html.erb
<%= form_with(model: list) do |form| %>
  <% if list.errors.any? %>
    <div style="color: red">
      <h2><%= pluralize(list.errors.count, "error") %> prohibited this list from being saved:</h2>

      <ul>
        <% list.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field form-group">
    <%= form.label :title, style: "display: block", style: "font-weight: bolder" %>
    <%= form.text_field :title, class:"form-control" %>
  </div>

  <div>
    <%= form.label :author, style: "display: block", style: "font-weight: bolder" %>
    <%= form.text_field :author, class:"form-control" %>
  </div>

  <div>
    <%= form.label :genre, style: "display: block", style: "font-weight: bolder"  %>
    <%= form.text_field :genre, class:"form-control" %>
  </div>

  <div>
    <%= form.label :year, style: "display: block", style: "font-weight: bolder"  %>
    <%= form.text_field :year, class:"form-control" %>
    <br>
  </div>

  <div>
    <%= form.submit class:"btn btn-secondary" %>
  </div>
<% end %>

app/views/lists/_list.html.erb
<div id="<%= dom_id list %>" class="table table-striped">
  <p>
    <strong>Title:</strong>
    <%= list.title %>
  </p>

  <p>
    <strong>Author:</strong>
    <%= list.author %>
  </p>

  <p>
    <strong>Genre:</strong>
    <%= list.genre %>
  </p>

  <p>
    <strong>Year:</strong>
    <%= list.year %>
  </p>

</div>

app/views/lists/edit.html.erb
<h1>Editing book</h1>
<br/>
<%= render "form", list: @list %>

<br>

<div>
  <%= link_to "Show", @list, class:"btn btn-secondary" %> |
  <%= link_to "Back", lists_path, class:"btn btn-dark" %>
</div>

app/views/lists/index.html.erb
  <table class="table table-striped table-bordered table-hover">
    <thead class="thead-dark">
      <tr>
        <th>Title</th>
        <th>Author</th>
        <th>Year</th>
        <th>Genre</th>
        <th> </th>
      </tr>
    </thead>

    <tbody>
      <% @lists.each do |list| %>
        <tr>
          <td>
            <%= link_to list.title, list %>

          </td>
          
          <td><%= list.author %></td>
          <td><%= list.year %></td>
          <td><%= list.genre %></td>
          
        </tr>
        <% end %>
    </tbody>
  </table>

app/views/lists/new.html.erb
<h1>Add New Book</h1>

<%= render "form", list: @list %>

<br>
<div>
  <%= link_to "Back", lists_path, class:"btn btn-dark" %>
</div>

app/views/lists/show.html.erb
<div class="jumbotron">
  <h1 class="display-4"><%= @list.title %></h1>
  <p class="lead"><%= render @list %></p>
  <hr class="my-4">
  <%= link_to "Edit", edit_list_path(@list), class:"btn btn-secondary" %> |
  <%= link_to "Back", lists_path, class:"btn btn-dark" %>
</div>
<div>

<%= button_to 'Delete', @list, method: :delete, data: { confirm: 'Are you sure?' }, class: "btn btn-danger" %>

</div>